import Head from "next/head";
import NavBar from "./nav/navBar";
import Footer from "./footer";
import { useAuth } from "../context/authContext";
import { useEffect } from "react";
import { useRouter } from "next/router";

type Props = {
  title: string;
  privateRoute: boolean;
  children: JSX.Element;
};
export const Layout = ({ children, privateRoute, title }: Props) => {
  const { userInfo, loading } = useAuth();
  const router = useRouter();

  if (privateRoute) {
    useEffect(() => {
      // redirect to login if user is not logged in
      if (!userInfo) {
        router.push("/login");
      }
    }, [userInfo, router]);

    // show loading indicator while the auth provider is still loading
    if (loading) {
      return <h1>Application Loading</h1>;
    }

    // if auth initialized with a valid currentUser show protected page
    if (!loading && userInfo) {
      return (
        <div className="flex flex-col h-screen justify-between">
          <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <NavBar />
          <main className="mb-auto">{children}</main>
          <Footer />
        </div>
      );
    }
  }

  return (
    <div className="flex flex-col h-screen justify-between">
      <Head>
        <title>Eagles Mere Park Association</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="mb-auto">{children}</main>
      <Footer />
    </div>
  );
};
