import Head from "next/head";

import NavBar from "./nav/navBar";
export const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Eagles Mere Park Association</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>{children}</main>
    </>
  );
};
