import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/nav/navBar";
import { useAuth } from "../context/authContext";

// Main landing page
const Home: NextPage = () => {
  const { currentUser, userInfo } = useAuth();

  console.log(userInfo);
  return (
    <div className="">
      <Head>
        <title>Eagles Mere Park Association</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>Home Page</main>
    </div>
  );
};

export default Home;
