import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/nav/navBar";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>Home Page</main>
    </div>
  );
};

export default Home;
