import Link from "next/link";
import Head from "next/head";
import type { NextPage } from "next";
import { useAuth } from "../context/authContext";
import { useState } from "react";
import { useRouter } from "next/router";

const Profile: NextPage = () => {
  const { userInfo } = useAuth();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Profile - Eagles Mere Park Association</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Profile</h1>
        <p>Welcome, {userInfo?.firstName || "Guest"}</p>

        {/* Grid of user information */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          <div className="bg-gray-100 p-4 rounded-lg">
            <h2 className="text-xl font-bold text-gray-800">
              Personal Information
            </h2>
            <p className="text-gray-600 m-2">
              {userInfo?.firstName} {userInfo?.lastName}
            </p>
            <p className="text-gray-600 m-2">{userInfo?.email}</p>
            <p className="text-gray-600 m-2">{userInfo?.phone}</p>
          </div>
          <div className="bg-gray-100 p-4 rounded-lg">
            <h2 className="text-xl font-bold text-gray-800">Address</h2>
            <p className="text-gray-600 m-2">{userInfo?.address}</p>
            <p className="text-gray-600 m-2">
              {userInfo?.city}, {userInfo?.state} {userInfo?.zip}
            </p>
          </div>
          <div className="bg-gray-100 p-4 rounded-lg">
            <h2 className="text-xl font-bold text-gray-800">Membership</h2>
            <p className="text-gray-600 m-2">{userInfo?.membership}</p>
            <p className="text-gray-600 m-2">
              {userInfo?.membershipExpiration}
            </p>
          </div>

          {/* Link to edit profile */}
          <div className="bg-gray-100 p-4 rounded-lg">
            <h2 className="text-xl font-bold text-gray-800">Edit Profile</h2>
            <Link href="/profile/edit">
              <a className="text-gray-600 m-2">Edit Profile</a>
            </Link>
          </div>

          {/* Link to change password */}
          <div className="bg-gray-100 p-4 rounded-lg">
            <h2 className="text-xl font-bold text-gray-800">Change Password</h2>
            <Link href="/profile/change-password">
              <a className="text-gray-600 m-2">Change Password</a>
            </Link>
          </div>
        </div>

        {/* Link to logout */}
        <Link href="/profile/logout">
          <a className="text-gray-600 m-2">Logout</a>
        </Link>
      </main>
      {/* Footer */}

      <footer className="bg-gray-800 text-white p-4 text-center">
        <div className="container mx-auto">
          <p className="text-sm">
            &copy; {new Date().getFullYear()} Eagles Mere Park Association
          </p>
        </div>
      </footer>
    </>
  );
};

export default Profile;
